### ISSUE TITLE
Fail to run master/agent under gcc 7.1.0 in centos 7

### ISSUE THREAD

**Issue by Devilbilly** [twhuang-uiuc/DtCraft#1]
By following the instruction of DtCraft Distributed Mode (Single Host), 
I tried to run bin/master and bin/agent, however, it crashed. 

$ ./master 
terminate called after throwing an instance of 'std::system_error'
  what():  unshare failed: Invalid argument
Abort (core dumped)

**Comment by clin99** [comment]
Could you use `uname -r` to check  the Linux kernel version of your machine?

**Comment by Devilbilly** [comment]
Linux 3.10.0-514.21.1.el7.x86_64, is this kernel too old? I can run examples without any problems.

**Comment by clin99** [comment]
To run under distributed mode, the Linux kernel version should be at least 3.8 or higher.

**Comment by Devilbilly** [comment]
I guess my kernel version is higher than 3.8?

**Comment by Devilbilly** [comment]
I'll manually enable user namespace and see if this solve this problem.

**Comment by Devilbilly** [comment]
Problem solved using 
$ grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
$ reboot

In centos 7, user namespace is a technology preview feature.

**Comment by tsung-wei-huang** [comment]
This is due to the setup of Linux container in DtCraft. We require "user namespace" to be enabled by your OS.
