### ISSUE TITLE
unittest/archive.sh fail

### ISSUE THREAD

**Issue by Devilbilly** [twhuang-uiuc/DtCraft#2]
Centos7, Linux 3.10.0-514.21.1.el7.x86_64
gcc 7.1.0

=====================================

   DtCraft 0.2.1: ./test-suite.log
=====================================

# TOTAL: 9
# PASS:  8
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: unittest/archive.sh
=========================

0.010 s: ArchiverTest.BinaryPOD
0.020 s: ArchiverTest.BinaryStruct
0.023 s: ArchiverTest.BinaryBasicString
1.854 s: ArchiverTest.BinaryVector
1.155 s: ArchiverTest.BinaryDeque
1.573 s: ArchiverTest.BinaryList
1.573 s: ArchiverTest.BinaryForwardList
2.374 s: ArchiverTest.BinaryMap
2.053 s: ArchiverTest.BinaryUnorderedMap
1.608 s: ArchiverTest.BinarySet
1.524 s: ArchiverTest.BinaryArray
0.002 s: ArchiverTest.BinaryVariant
0.003 s: ArchiverTest.SmartPointer
0.002 s: ArchiverTest.ErrorCode

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lt-archive is a Catch v2.0.1 host application.
Run with -? for options
-------------------------------------------------------------------------------
ArchiverTest.BinaryAtomicity
-------------------------------------------------------------------------------
unittest/archive.cpp:764
...............................................................................

unittest/archive.cpp:764: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  SIGTERM - Termination request signal

0.000 s: ArchiverTest.BinaryAtomicity
===============================================================================
test cases:    15 |    14 passed | 1 failed
assertions: 98226 | 98225 passed | 1 failed

**Comment by tsung-wei-huang** [comment]
Thanks for the report. This is due to the timeout limit we specify for each unittest. By default, the limit is one minute. Depending on your machine, you might enlarge this limit in `unittest/archive.sh` from 1m to a larger value. We will make this value dynamic in the next release.
